debug: true
logging:
  level:
    root: debug
    tech:
      wetech:
        admin:
          mapper: trace
server:
  port: 8889
  servlet:
    context-path: /tt
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 1
      max-active: 20
      min-idle: 1
      stat-view-servlet:
        allow: true
      test-on-borrow: true
    password: 123456
    url: jdbc:mysql://192.168.150.128:3306/wetech_admin?useUnicode=true&characterEncoding=utf-8
    username: root
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
  thymeleaf:
    cache: false